services:
  webapp:
    build: .
    ports:
      - "3000:3000"
    environment:
      - USERNAME=test1
      - PASSWORD=testpass1
    depends_on:
      - git-server
      - sonarqube

  git-server:
    image: gitea/gitea:latest
    container_name: git-server
    environment:
      - USER_NAME=test2
      - USER_EMAIL=test2@testmail.com
    ports:
      - "3001:3000"
    volumes:
      - ./git-data:/data
    restart: unless-stopped

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_USERNAME=test3
      - SONARQUBE_PASSWORD=test3
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgres_data:
  git-data: